channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
